class name of numpy is ndarray

Numpy is a python library used for working with arrays

In python we have lists thet serves the purpose of arrays,but they are slow to process.

Numpy aims to provide an array object that is upto 50* faster than traditional Python list.

The array object in numpy is called ndarry,it provides a lots of supporting functions that make working with ndarry very easy

Arrays are very frequently used in data science , where speed and resources and very important

Collection of homogenous data

It does not support heterogenous data

size is fixed

In [ ]:
import numpy as np

In [ ]:
import numpy as np

x = np.ndarray([1,2,5,6])

print(x)

[[[[ 5.00124735e-310  0.00000000e+000  6.67433625e-310  1.65575615e-116
     6.67431579e-310  6.67433625e-310]
   [ 5.04199728e-136  6.67431579e-310  6.67433625e-310  2.05698503e-175
     6.67431579e-310  6.67433625e-310]
   [ 6.43879145e+091  6.67431579e-310  6.67433625e-310 -1.59523652e-230
     6.67431579e-310  6.67433625e-310]
   [-8.23548975e-215  6.67431579e-310  6.67433625e-310 -2.98351608e-022
     6.67431579e-310  6.67433625e-310]
   [-1.98168549e+002  6.67431579e-310  6.67433625e-310 -1.55964706e-006
     6.67431579e-310  6.67433625e-310]]

  [[-7.47732907e+272  6.67431579e-310  6.67433625e-310 -2.37248833e-011
     6.67431571e-310  6.67433625e-310]
   [-6.50817626e+220  6.67431571e-310  6.67433625e-310 -3.27680768e+028
     6.67431571e-310  6.67433625e-310]
   [-1.20471793e-009  6.67431571e-310  6.67433625e-310  7.68773660e+208
     6.67431571e-310  6.67433625e-310]
   [-1.13678384e+268  6.67431571e-310  6.67433625e-310  3.90815900e+016
     6.67431571e-310  6.67433625e-310]

In [ ]:
import numpy as np

x = np.array([1,2,5,6])

print(x)

[1 2 5 6]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
print(x.ndim)

1


In [ ]:
print(x.shape)

(4,)


In [ ]:
import numpy as np

x = np.array([[1,2,3,44],[1,2,3,4]])

print(x)
print(x.shape)
print(x.ndim)

[[ 1  2  3 44]
 [ 1  2  3  4]]
(2, 4)
2


In [ ]:
import numpy as np

x = np.array([[1,2,3,44,6],[1,2,3,4,5],[1,2,4,6,7],[4,5,6,7,8]])

print(x)
print(x.shape)
print(x.ndim)

[[ 1  2  3 44  6]
 [ 1  2  3  4  5]
 [ 1  2  4  6  7]
 [ 4  5  6  7  8]]
(4, 5)
2


In [ ]:
import numpy as np

x = np.array([[1,2,3,44,7,8],[1,2,3,4,5,6]])

print(x)
print(x.shape)
print(x.ndim)

[[ 1  2  3 44  7  8]
 [ 1  2  3  4  5  6]]
(2, 6)
2


In [ ]:
x = np.array([[[2,4,5],[3,4,5],],[[3,4,5],[3,4,5]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[2 4 5]
  [3 4 5]]

 [[3 4 5]
  [3 4 5]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)


In [ ]:
#(2,4,2)

x = np.array([[[2,2],[2,3],[4,4],[5,5]],
             [[2,2],[3,4],[5,6],[7,8]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[2 2]
  [2 3]
  [4 4]
  [5 5]]

 [[2 2]
  [3 4]
  [5 6]
  [7 8]]]
<class 'numpy.ndarray'>
3
(2, 4, 2)


In [ ]:
#(3,2,3)

x = np.array([[[2,3,4],[2,3,4]],
             [[1,2,3],[3,5,6]],
             [[3,4,5],[7,8,9]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[2 3 4]
  [2 3 4]]

 [[1 2 3]
  [3 5 6]]

 [[3 4 5]
  [7 8 9]]]
<class 'numpy.ndarray'>
3
(3, 2, 3)


In [ ]:
#(4,2,2)
x = np.array([[[2,2],[4,6]],
             [[2,5],[6,8]],
             [[5,8],[6,8]],
             [[7,7],[78,9]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[ 2  2]
  [ 4  6]]

 [[ 2  5]
  [ 6  8]]

 [[ 5  8]
  [ 6  8]]

 [[ 7  7]
  [78  9]]]
<class 'numpy.ndarray'>
3
(4, 2, 2)


In [ ]:

import numpy as np
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros((2,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [ ]:
np.ones((3,2,5),dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(20,80)

array([20.        , 21.2244898 , 22.44897959, 23.67346939, 24.89795918,
       26.12244898, 27.34693878, 28.57142857, 29.79591837, 31.02040816,
       32.24489796, 33.46938776, 34.69387755, 35.91836735, 37.14285714,
       38.36734694, 39.59183673, 40.81632653, 42.04081633, 43.26530612,
       44.48979592, 45.71428571, 46.93877551, 48.16326531, 49.3877551 ,
       50.6122449 , 51.83673469, 53.06122449, 54.28571429, 55.51020408,
       56.73469388, 57.95918367, 59.18367347, 60.40816327, 61.63265306,
       62.85714286, 64.08163265, 65.30612245, 66.53061224, 67.75510204,
       68.97959184, 70.20408163, 71.42857143, 72.65306122, 73.87755102,
       75.10204082, 76.32653061, 77.55102041, 78.7755102 , 80.        ])

In [ ]:
np.full((3,4),10,dtype=int)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.random((3,2,2))

array([[[0.01001605, 0.63048976],
        [0.82459395, 0.47164775]],

       [[0.09304577, 0.45333641],
        [0.79553998, 0.36479263]],

       [[0.85524255, 0.41032747],
        [0.86517126, 0.18944254]]])

In [ ]:
np.random.randint(100,200,(3,2,2))

array([[[164, 169],
        [115, 105]],

       [[185, 189],
        [178, 165]],

       [[197, 135],
        [154, 177]]])

In [ ]:
np.random.randint(100,size=(3,2,2))

array([[[ 6, 93],
        [86, 76]],

       [[ 8, 54],
        [11, 79]],

       [[34, 39],
        [65, 28]]])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#add
np.add(a,b)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
#multiple
np.multiply(a,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
#division
np.divide(a,b)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [ ]:
#power
np.power(a,b)

array([[         1,        256,      19683],
       [   1048576,   48828125, 2176782336]])

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.floor(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [3. 2. 4. 5. 9.]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.ceil(a)

print(y)


[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 6. 9.]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.round(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 6. 9.]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.rint(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 6. 9.]]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(type(a))

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.dtype)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
float64


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.dtype)

[['1' '2' '3' '4' '7']
 ['3.5' '2' '4.6' '5.8' '9.0']]
<U32


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

x = a.astype(complex)

print(x)

print(a.dtype)

[['1' '2' '3' '4' '7']
 ['3.5' '2' '4.6' '5.8' '9.0']]
[[1. +0.j 2. +0.j 3. +0.j 4. +0.j 7. +0.j]
 [3.5+0.j 2. +0.j 4.6+0.j 5.8+0.j 9. +0.j]]
<U32
